global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Localization;
global using FluentValidation;
global using Newtonsoft.Json;
global using Book.Models;
global using Book.Services;
global using Book.Shared;
