//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Book.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alcohol.
        /// </summary>
        internal static string Alcohol {
            get {
                return ResourceManager.GetString("Alcohol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string AllItemsText {
            get {
                return ResourceManager.GetString("AllItemsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to calling Page.
        /// </summary>
        internal static string BackPage {
            get {
                return ResourceManager.GetString("BackPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Summary.
        /// </summary>
        internal static string BackToSummary {
            get {
                return ResourceManager.GetString("BackToSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back up.
        /// </summary>
        internal static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup file prefix.
        /// </summary>
        internal static string BackupPrefix {
            get {
                return ResourceManager.GetString("BackupPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bimonthly.
        /// </summary>
        internal static string Bimonthly {
            get {
                return ResourceManager.GetString("Bimonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit.Besql.
        /// </summary>
        internal static string BitBesql {
            get {
                return ResourceManager.GetString("BitBesql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit Platform Logo.
        /// </summary>
        internal static string BitBesqlLogo {
            get {
                return ResourceManager.GetString("BitBesqlLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit.Besql enables using a EFCore compatible SQLite database that persits in the Browser&apos;s cache.
        /// </summary>
        internal static string BitBesqlText {
            get {
                return ResourceManager.GetString("BitBesqlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blazor Logo.
        /// </summary>
        internal static string BlazorLogo {
            get {
                return ResourceManager.GetString("BlazorLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blazor lets you build interactive web UIs using C# instead of JavaScript. Blazor apps are composed of reusable web UI components implemented using C#, HTML, and CSS. Both client and server code is written in C#, allowing you to share code and libraries..
        /// </summary>
        internal static string BlazorText {
            get {
                return ResourceManager.GetString("BlazorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blazor WebAssembly (Wasm).
        /// </summary>
        internal static string BlazorWasm {
            get {
                return ResourceManager.GetString("BlazorWasm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        internal static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Name.
        /// </summary>
        internal static string BookName {
            get {
                return ResourceManager.GetString("BookName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        internal static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All changes will be permanently lost.
        /// </summary>
        internal static string ChangesLost {
            get {
                return ResourceManager.GetString("ChangesLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All changes made after {0} will be permanently lost.
        /// </summary>
        internal static string ChangesLostBU {
            get {
                return ResourceManager.GetString("ChangesLostBU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Chart.
        /// </summary>
        internal static string Chart {
            get {
                return ResourceManager.GetString("Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Menu.
        /// </summary>
        internal static string CloseMenu {
            get {
                return ResourceManager.GetString("CloseMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clothing.
        /// </summary>
        internal static string Clothing {
            get {
                return ResourceManager.GetString("Clothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Entry.
        /// </summary>
        internal static string CopyEntry {
            get {
                return ResourceManager.GetString("CopyEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create 1 Entry.
        /// </summary>
        internal static string Create1Entry {
            get {
                return ResourceManager.GetString("Create1Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Entries.
        /// </summary>
        internal static string CreateEntries {
            get {
                return ResourceManager.GetString("CreateEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        internal static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        internal static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        internal static string DarkMode {
            get {
                return ResourceManager.GetString("DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any changes you make are saved in an SQLite database. It is highly recommended to periodically back this up. Last backup: {0}.
        /// </summary>
        internal static string DatabaseAlertMessage {
            get {
                return ResourceManager.GetString("DatabaseAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the database to a file.
        /// </summary>
        internal static string DatabaseBackupText {
            get {
                return ResourceManager.GetString("DatabaseBackupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the current database and use one with default Types and no Entries.
        /// </summary>
        internal static string DatabaseDeleteText {
            get {
                return ResourceManager.GetString("DatabaseDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite saved changes with Demonstration data.
        /// </summary>
        internal static string DatabaseDemoAcptToolTip {
            get {
                return ResourceManager.GetString("DatabaseDemoAcptToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace the database with demonstration data.
        /// </summary>
        internal static string DatabaseDemoText {
            get {
                return ResourceManager.GetString("DatabaseDemoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace the database with a previous backup.
        /// </summary>
        internal static string DatabaseRestoreText {
            get {
                return ResourceManager.GetString("DatabaseRestoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Version.
        /// </summary>
        internal static string DatabaseVersion {
            get {
                return ResourceManager.GetString("DatabaseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dated.
        /// </summary>
        internal static string Dated {
            get {
                return ResourceManager.GetString("Dated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Entry.
        /// </summary>
        internal static string DeleteEntry {
            get {
                return ResourceManager.GetString("DeleteEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Entry Type.
        /// </summary>
        internal static string DeleteEntryType {
            get {
                return ResourceManager.GetString("DeleteEntryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Saved Changes.
        /// </summary>
        internal static string DeleteSavedChanges {
            get {
                return ResourceManager.GetString("DeleteSavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} Summary Type.
        /// </summary>
        internal static string DeleteSTypeAccLabel {
            get {
                return ResourceManager.GetString("DeleteSTypeAccLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Summary Type.
        /// </summary>
        internal static string DeleteSummaryType {
            get {
                return ResourceManager.GetString("DeleteSummaryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} Entry for {1}.
        /// </summary>
        internal static string DeleteTransAccLabel {
            get {
                return ResourceManager.GetString("DeleteTransAccLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} Entry Type.
        /// </summary>
        internal static string DeleteTTypeAccLabel {
            get {
                return ResourceManager.GetString("DeleteTTypeAccLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Entry.
        /// </summary>
        internal static string EditEntry {
            get {
                return ResourceManager.GetString("EditEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit EntryType.
        /// </summary>
        internal static string EditEntryType {
            get {
                return ResourceManager.GetString("EditEntryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Summary Type.
        /// </summary>
        internal static string EditSummaryType {
            get {
                return ResourceManager.GetString("EditSummaryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Framework Core.
        /// </summary>
        internal static string EFCore {
            get {
                return ResourceManager.GetString("EFCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EF Core Logo.
        /// </summary>
        internal static string EFCoreLogo {
            get {
                return ResourceManager.GetString("EFCoreLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Framework (EF) Core is an object-database mapper for .NET..
        /// </summary>
        internal static string EFCoreText {
            get {
                return ResourceManager.GetString("EFCoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date must be specified.
        /// </summary>
        internal static string EndDateReqd {
            get {
                return ResourceManager.GetString("EndDateReqd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Year.
        /// </summary>
        internal static string EndYear {
            get {
                return ResourceManager.GetString("EndYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entertainment.
        /// </summary>
        internal static string Entertainment {
            get {
                return ResourceManager.GetString("Entertainment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entries.
        /// </summary>
        internal static string Entries {
            get {
                return ResourceManager.GetString("Entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Entries Filtered.
        /// </summary>
        internal static string EntriesFiltered {
            get {
                return ResourceManager.GetString("EntriesFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry.
        /// </summary>
        internal static string Entry {
            get {
                return ResourceManager.GetString("Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry for.
        /// </summary>
        internal static string EntryFor {
            get {
                return ResourceManager.GetString("EntryFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Entry must have a date.
        /// </summary>
        internal static string EntryMustBeDated {
            get {
                return ResourceManager.GetString("EntryMustBeDated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Type.
        /// </summary>
        internal static string EntryType {
            get {
                return ResourceManager.GetString("EntryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Types.
        /// </summary>
        internal static string EntryTypes {
            get {
                return ResourceManager.GetString("EntryTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} Expenditure.
        /// </summary>
        internal static string Expenditure {
            get {
                return ResourceManager.GetString("Expenditure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Expenditure Chart.
        /// </summary>
        internal static string ExpenditureChart {
            get {
                return ResourceManager.GetString("ExpenditureChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluent Validation.
        /// </summary>
        internal static string FluentValidation {
            get {
                return ResourceManager.GetString("FluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluent Validation Logo.
        /// </summary>
        internal static string FluentValidationLogo {
            get {
                return ResourceManager.GetString("FluentValidationLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food.
        /// </summary>
        internal static string Food {
            get {
                return ResourceManager.GetString("Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        internal static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fun.
        /// </summary>
        internal static string Fun {
            get {
                return ResourceManager.GetString("Fun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A validation library for .NET that uses a fluent interface and lambda expressions for building strongly-typed validation rules..
        /// </summary>
        internal static string FVText {
            get {
                return ResourceManager.GetString("FVText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groceries.
        /// </summary>
        internal static string Groceries {
            get {
                return ResourceManager.GetString("Groceries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide {0} Entry Types.
        /// </summary>
        internal static string HideEntryTypes {
            get {
                return ResourceManager.GetString("HideEntryTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday.
        /// </summary>
        internal static string Holiday {
            get {
                return ResourceManager.GetString("Holiday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Household.
        /// </summary>
        internal static string Household {
            get {
                return ResourceManager.GetString("Household", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        internal static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Information.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Backup Date.
        /// </summary>
        internal static string LastBackupDate {
            get {
                return ResourceManager.GetString("LastBackupDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Mode.
        /// </summary>
        internal static string LightMode {
            get {
                return ResourceManager.GetString("LightMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Entries for EntryType.
        /// </summary>
        internal static string ListEntriesForEntryType {
            get {
                return ResourceManager.GetString("ListEntriesForEntryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Entries for Summary Type.
        /// </summary>
        internal static string ListEntriesForSummaryType {
            get {
                return ResourceManager.GetString("ListEntriesForSummaryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Demo Data.
        /// </summary>
        internal static string LoadDemoData {
            get {
                return ResourceManager.GetString("LoadDemoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Entries ....
        /// </summary>
        internal static string LoadingEntries {
            get {
                return ResourceManager.GetString("LoadingEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        internal static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Information.
        /// </summary>
        internal static string MoreInformation {
            get {
                return ResourceManager.GetString("MoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book enables the recording of Entries via the New Entry button while the Summary (Home) page shows monthly balances. An Entry has a Type, these Types are collated into Summaries that are used as columns on the Summary page. You can add Summaries by pressing the menu button and then the Types option. This page also lets you create and edit Entry Types..
        /// </summary>
        internal static string MoreInfoText {
            get {
                return ResourceManager.GetString("MoreInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mortgage.
        /// </summary>
        internal static string Mortgage {
            get {
                return ResourceManager.GetString("Mortgage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MudBlazor.
        /// </summary>
        internal static string MudBlazor {
            get {
                return ResourceManager.GetString("MudBlazor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MudBlazor Logo.
        /// </summary>
        internal static string MudBlazorLogo {
            get {
                return ResourceManager.GetString("MudBlazorLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MudBlazor is a UI component library written from the ground up for Blazor..
        /// </summary>
        internal static string MudBlazorText {
            get {
                return ResourceManager.GetString("MudBlazorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Entry.
        /// </summary>
        internal static string NewEntry {
            get {
                return ResourceManager.GetString("NewEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Entry Type.
        /// </summary>
        internal static string NewEntryType {
            get {
                return ResourceManager.GetString("NewEntryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Summary Type.
        /// </summary>
        internal static string NewSummaryType {
            get {
                return ResourceManager.GetString("NewSummaryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No backup recorded.
        /// </summary>
        internal static string NoBackupRecorded {
            get {
                return ResourceManager.GetString("NoBackupRecorded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Entries Found.
        /// </summary>
        internal static string NoEntriesFound {
            get {
                return ResourceManager.GetString("NoEntriesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Entry Types for.
        /// </summary>
        internal static string NoEntryTypesFor {
            get {
                return ResourceManager.GetString("NoEntryTypesFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Menu.
        /// </summary>
        internal static string OpenMenu {
            get {
                return ResourceManager.GetString("OpenMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {first_item}-{last_item} of {all_items}.
        /// </summary>
        internal static string PagerInfoFormat {
            get {
                return ResourceManager.GetString("PagerInfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quaterly.
        /// </summary>
        internal static string Quaterly {
            get {
                return ResourceManager.GetString("Quaterly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent.
        /// </summary>
        internal static string Rent {
            get {
                return ResourceManager.GetString("Rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows per Page:.
        /// </summary>
        internal static string RowsPerPage {
            get {
                return ResourceManager.GetString("RowsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Entry.
        /// </summary>
        internal static string SaveEntry {
            get {
                return ResourceManager.GetString("SaveEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Entry Type.
        /// </summary>
        internal static string SaveEntryType {
            get {
                return ResourceManager.GetString("SaveEntryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Settings.
        /// </summary>
        internal static string SaveSettings {
            get {
                return ResourceManager.GetString("SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Summary Type.
        /// </summary>
        internal static string SaveSummaryType {
            get {
                return ResourceManager.GetString("SaveSummaryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string SettingValue {
            get {
                return ResourceManager.GetString("SettingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show {0} Entry Types.
        /// </summary>
        internal static string ShowEntryTypes {
            get {
                return ResourceManager.GetString("ShowEntryTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Year.
        /// </summary>
        internal static string StartYear {
            get {
                return ResourceManager.GetString("StartYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summaries.
        /// </summary>
        internal static string Summaries {
            get {
                return ResourceManager.GetString("Summaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary Type.
        /// </summary>
        internal static string SummaryType {
            get {
                return ResourceManager.GetString("SummaryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takeaway.
        /// </summary>
        internal static string Takeaway {
            get {
                return ResourceManager.GetString("Takeaway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to times.
        /// </summary>
        internal static string Times {
            get {
                return ResourceManager.GetString("Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trackor.
        /// </summary>
        internal static string Trackor {
            get {
                return ResourceManager.GetString("Trackor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trackor Logo.
        /// </summary>
        internal static string TrackorLogo {
            get {
                return ResourceManager.GetString("TrackorLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trackor is a Blazor WASM application that uses many of the above packages. I shamelessly used it as both an inspiration and direct code source..
        /// </summary>
        internal static string TrackorText {
            get {
                return ResourceManager.GetString("TrackorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create {0} Entries?.
        /// </summary>
        internal static string TransCopyAccLabelM {
            get {
                return ResourceManager.GetString("TransCopyAccLabelM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create 1 Entry?.
        /// </summary>
        internal static string TransCopyAccLabelS {
            get {
                return ResourceManager.GetString("TransCopyAccLabelS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy {0} {1} Entry.
        /// </summary>
        internal static string TransCopyTitle {
            get {
                return ResourceManager.GetString("TransCopyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} Entries.
        /// </summary>
        internal static string TransListNameM {
            get {
                return ResourceManager.GetString("TransListNameM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} Entry.
        /// </summary>
        internal static string TransListNameS {
            get {
                return ResourceManager.GetString("TransListNameS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} Entries in {2} {3}.
        /// </summary>
        internal static string TransListTitleM {
            get {
                return ResourceManager.GetString("TransListTitleM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} Entry in {2} {3}.
        /// </summary>
        internal static string TransListTitleS {
            get {
                return ResourceManager.GetString("TransListTitleS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types.
        /// </summary>
        internal static string Types {
            get {
                return ResourceManager.GetString("Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilities.
        /// </summary>
        internal static string Utilities {
            get {
                return ResourceManager.GetString("Utilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Another Year.
        /// </summary>
        internal static string ViewAnotherYear {
            get {
                return ResourceManager.GetString("ViewAnotherYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visited {0} times.
        /// </summary>
        internal static string VisitCount {
            get {
                return ResourceManager.GetString("VisitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visited.
        /// </summary>
        internal static string Visited {
            get {
                return ResourceManager.GetString("Visited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wages.
        /// </summary>
        internal static string Wages {
            get {
                return ResourceManager.GetString("Wages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING.
        /// </summary>
        internal static string WarningUpp {
            get {
                return ResourceManager.GetString("WarningUpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        internal static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work.
        /// </summary>
        internal static string Work {
            get {
                return ResourceManager.GetString("Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Expenses.
        /// </summary>
        internal static string WorkExpenses {
            get {
                return ResourceManager.GetString("WorkExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Year Chart.
        /// </summary>
        internal static string YearChart {
            get {
                return ResourceManager.GetString("YearChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly.
        /// </summary>
        internal static string Yearly {
            get {
                return ResourceManager.GetString("Yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Expenditure.
        /// </summary>
        internal static string YExpenditure {
            get {
                return ResourceManager.GetString("YExpenditure", resourceCulture);
            }
        }
    }
}
